/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Rene' at '12/4/13 5:03 PM' with Gradle 1.11-20131204091757+0000
 *
 * @author Rene, @date 12/4/13 5:03 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
